RA:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      Rev1:
        type: position_controllers/JointPositionController
        joint: Rev1
        pid: {p: 1.0, i: 1.0, d: 1.0}
      Rev2:
        type: positiont_controllers/JointPositionController
        joint: Rev2
        pid: {p: 1.0, i: 1.0, d: 1.0}
      Rev3:
        type: position_controllers/JointPositionController
        joint: Rev3
        pid: {p: 1.0, i: 1.0, d: 1.0}
      Rev4:
        type: positiont_controllers/JointPositionController
        joint: Rev4
        pid: {p: 1.0, i: 1.0, d: 1.0}
      Rev5:
        type: position_controllers/JointPositionController
        joint: Rev5
        pid: {p: 1.0, i: 1.0, d: 1.0}
      Rev6:
        type: position_controllers/JointPositionController
        joint: Rev6
        pid: {p: 1.0, i: 1.0, d: 1.0}
