#!/usr/bin/env python

from __future__ import print_function

import rospy
from std_msgs.msg import String
import time
import math

from ODrive_Interface_test.srv import *

rospy.wait_for_service('drive_axis')
rospy.wait_for_service('axis_position')
drive_axis = rospy.ServiceProxy('drive_axis', driver)
axis_position = rospy.ServiceProxy('axis_position', feedback)

resp1 = axis_position.call(feedbackRequest(6))
print(resp1)

resp2 = drive_axis.call(driverRequest(6, 100000))
print(resp2)

time.sleep(2)

resp1 = axis_position.call(feedbackRequest(6))
print(resp1)

resp2 = drive_axis.call(driverRequest(6, 0))
print(resp2)

resp1 = axis_position.call(feedbackRequest(6))
print(resp1)
