// Generated by gencpp from file ODrive_Interface_test/feedbackResponse.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_TEST_MESSAGE_FEEDBACKRESPONSE_H
#define ODRIVE_INTERFACE_TEST_MESSAGE_FEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ODrive_Interface_test
{
template <class ContainerAllocator>
struct feedbackResponse_
{
  typedef feedbackResponse_<ContainerAllocator> Type;

  feedbackResponse_()
    : position(0.0)  {
    }
  feedbackResponse_(const ContainerAllocator& _alloc)
    : position(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct feedbackResponse_

typedef ::ODrive_Interface_test::feedbackResponse_<std::allocator<void> > feedbackResponse;

typedef boost::shared_ptr< ::ODrive_Interface_test::feedbackResponse > feedbackResponsePtr;
typedef boost::shared_ptr< ::ODrive_Interface_test::feedbackResponse const> feedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator1> & lhs, const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator1> & lhs, const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ODrive_Interface_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4e11b3af29ed247b2bd150d3f4540f9";
  }

  static const char* value(const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4e11b3af29ed247ULL;
  static const uint64_t static_value2 = 0xb2bd150d3f4540f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ODrive_Interface_test/feedbackResponse";
  }

  static const char* value(const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 position\n"
"\n"
;
  }

  static const char* value(const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ODrive_Interface_test::feedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODRIVE_INTERFACE_TEST_MESSAGE_FEEDBACKRESPONSE_H
