// Generated by gencpp from file ODrive_Interface_test/requested_state.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATE_H
#define ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATE_H

#include <ros/service_traits.h>


#include <ODrive_Interface_test/requested_stateRequest.h>
#include <ODrive_Interface_test/requested_stateResponse.h>


namespace ODrive_Interface_test
{

struct requested_state
{

typedef requested_stateRequest Request;
typedef requested_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct requested_state
} // namespace ODrive_Interface_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ODrive_Interface_test::requested_state > {
  static const char* value()
  {
    return "b06410045851cc21cdfe462a30e6cdb3";
  }

  static const char* value(const ::ODrive_Interface_test::requested_state&) { return value(); }
};

template<>
struct DataType< ::ODrive_Interface_test::requested_state > {
  static const char* value()
  {
    return "ODrive_Interface_test/requested_state";
  }

  static const char* value(const ::ODrive_Interface_test::requested_state&) { return value(); }
};


// service_traits::MD5Sum< ::ODrive_Interface_test::requested_stateRequest> should match
// service_traits::MD5Sum< ::ODrive_Interface_test::requested_state >
template<>
struct MD5Sum< ::ODrive_Interface_test::requested_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ODrive_Interface_test::requested_state >::value();
  }
  static const char* value(const ::ODrive_Interface_test::requested_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ODrive_Interface_test::requested_stateRequest> should match
// service_traits::DataType< ::ODrive_Interface_test::requested_state >
template<>
struct DataType< ::ODrive_Interface_test::requested_stateRequest>
{
  static const char* value()
  {
    return DataType< ::ODrive_Interface_test::requested_state >::value();
  }
  static const char* value(const ::ODrive_Interface_test::requested_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ODrive_Interface_test::requested_stateResponse> should match
// service_traits::MD5Sum< ::ODrive_Interface_test::requested_state >
template<>
struct MD5Sum< ::ODrive_Interface_test::requested_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ODrive_Interface_test::requested_state >::value();
  }
  static const char* value(const ::ODrive_Interface_test::requested_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ODrive_Interface_test::requested_stateResponse> should match
// service_traits::DataType< ::ODrive_Interface_test::requested_state >
template<>
struct DataType< ::ODrive_Interface_test::requested_stateResponse>
{
  static const char* value()
  {
    return DataType< ::ODrive_Interface_test::requested_state >::value();
  }
  static const char* value(const ::ODrive_Interface_test::requested_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATE_H
