// Generated by gencpp from file ODrive_Interface_test/requested_stateRequest.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATEREQUEST_H
#define ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ODrive_Interface_test
{
template <class ContainerAllocator>
struct requested_stateRequest_
{
  typedef requested_stateRequest_<ContainerAllocator> Type;

  requested_stateRequest_()
    : axis(0)
    , requested_state(0)  {
    }
  requested_stateRequest_(const ContainerAllocator& _alloc)
    : axis(0)
    , requested_state(0)  {
  (void)_alloc;
    }



   typedef int16_t _axis_type;
  _axis_type axis;

   typedef int16_t _requested_state_type;
  _requested_state_type requested_state;





  typedef boost::shared_ptr< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct requested_stateRequest_

typedef ::ODrive_Interface_test::requested_stateRequest_<std::allocator<void> > requested_stateRequest;

typedef boost::shared_ptr< ::ODrive_Interface_test::requested_stateRequest > requested_stateRequestPtr;
typedef boost::shared_ptr< ::ODrive_Interface_test::requested_stateRequest const> requested_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator1> & lhs, const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.axis == rhs.axis &&
    lhs.requested_state == rhs.requested_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator1> & lhs, const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ODrive_Interface_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a10318c9ebc765320932e18d76aa3b6f";
  }

  static const char* value(const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa10318c9ebc76532ULL;
  static const uint64_t static_value2 = 0x0932e18d76aa3b6fULL;
};

template<class ContainerAllocator>
struct DataType< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ODrive_Interface_test/requested_stateRequest";
  }

  static const char* value(const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int16 axis\n"
"int16 requested_state\n"
;
  }

  static const char* value(const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.requested_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct requested_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ODrive_Interface_test::requested_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.axis);
    s << indent << "requested_state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.requested_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODRIVE_INTERFACE_TEST_MESSAGE_REQUESTED_STATEREQUEST_H
