// Generated by gencpp from file ODrive_Interface_test/velocity.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_TEST_MESSAGE_VELOCITY_H
#define ODRIVE_INTERFACE_TEST_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <ODrive_Interface_test/velocityRequest.h>
#include <ODrive_Interface_test/velocityResponse.h>


namespace ODrive_Interface_test
{

struct velocity
{

typedef velocityRequest Request;
typedef velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct velocity
} // namespace ODrive_Interface_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ODrive_Interface_test::velocity > {
  static const char* value()
  {
    return "6f5723450e3c67d0d72065dca6e91464";
  }

  static const char* value(const ::ODrive_Interface_test::velocity&) { return value(); }
};

template<>
struct DataType< ::ODrive_Interface_test::velocity > {
  static const char* value()
  {
    return "ODrive_Interface_test/velocity";
  }

  static const char* value(const ::ODrive_Interface_test::velocity&) { return value(); }
};


// service_traits::MD5Sum< ::ODrive_Interface_test::velocityRequest> should match
// service_traits::MD5Sum< ::ODrive_Interface_test::velocity >
template<>
struct MD5Sum< ::ODrive_Interface_test::velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ODrive_Interface_test::velocity >::value();
  }
  static const char* value(const ::ODrive_Interface_test::velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ODrive_Interface_test::velocityRequest> should match
// service_traits::DataType< ::ODrive_Interface_test::velocity >
template<>
struct DataType< ::ODrive_Interface_test::velocityRequest>
{
  static const char* value()
  {
    return DataType< ::ODrive_Interface_test::velocity >::value();
  }
  static const char* value(const ::ODrive_Interface_test::velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ODrive_Interface_test::velocityResponse> should match
// service_traits::MD5Sum< ::ODrive_Interface_test::velocity >
template<>
struct MD5Sum< ::ODrive_Interface_test::velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ODrive_Interface_test::velocity >::value();
  }
  static const char* value(const ::ODrive_Interface_test::velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ODrive_Interface_test::velocityResponse> should match
// service_traits::DataType< ::ODrive_Interface_test::velocity >
template<>
struct DataType< ::ODrive_Interface_test::velocityResponse>
{
  static const char* value()
  {
    return DataType< ::ODrive_Interface_test::velocity >::value();
  }
  static const char* value(const ::ODrive_Interface_test::velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODRIVE_INTERFACE_TEST_MESSAGE_VELOCITY_H
