#!/usr/bin/env python3

from __future__ import print_function

import rospy
from std_msgs.msg import String
from std_msgs.msg import Int32
import odrive
from odrive.enums import *
import time
import math

from nsra_odrive_interface.srv import *

positions = [0, 0, 0, 0, 0, 0]

hz = 20

print("Connecting...")
odrv1 = odrive.find_any(serial_number="20573882304E")
print("Connected to ODrive 1")

def drive_pub1(data):
    print("Axis 1: " + str(data.data))
    if abs(data.data-positions[0])*hz > 50000:
        odrv1.axis0.controller.config.vel_limit = abs(data.data-positions[0])*hz
    else:
        odrv1.axis0.controller.config.vel_limit = 50000
    odrv1.axis0.controller.input_pos = data.data
    #drive1.publish(int(data.data*(1024000)/math.pi))
    positions[0] = data.data

def drive_pub6(data):
    print("Axis 6: " + str(data.data))
    if abs(data.data-positions[5])*hz > 20000:
        odrv1.axis1.controller.config.vel_limit = abs(data.data-positions[5])*hz
    else:
        odrv1.axis1.controller.config.vel_limit = 20000
    odrv1.axis1.controller.input_pos = data.data
    #drive6.publish(int(data.data*(1024000)/math.pi))
    positions[5] = data.data

def axis_requested_state(req):
    print("Axis requested_state")

    if req.axis == 1:
        if req.requested_state == 0:
            odrv1.axis0.requested_state = AXIS_STATE_FULL_CALIBRATION_SEQUENCE
            while odrv1.axis0.current_state != AXIS_STATE_IDLE:
                time.sleep(0.1)
            odrv1.axis0.requested_state = AXIS_STATE_CLOSED_LOOP_CONTROL
        else:
            odrv1.axis0.requested_state = req.requested_state
    if req.axis == 6:
        if req.requested_state == 0:
            odrv1.axis1.requested_state = AXIS_STATE_FULL_CALIBRATION_SEQUENCE
            while odrv1.axis1.current_state != AXIS_STATE_IDLE:
                time.sleep(0.1)
            odrv1.axis1.requested_state = AXIS_STATE_CLOSED_LOOP_CONTROL
        else:
            odrv1.axis1.requested_state = req.requested_state

    return requested_stateResponse(True)

rospy.init_node('driver')

rospy.Subscriber("/nsra/drive_pub1", Int32, drive_pub1)
rospy.Subscriber("/nsra/drive_pub6", Int32, drive_pub6)

rospy.Subscriber("/dump_errors", Int32, dump_errors)

requested_state = rospy.Service('odrv1_requested_state', requested_state, axis_requested_state)

rospy.spin()
