controller_list:
  - name: /RA/controller/trajectory/Position
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [Rev1, Rev2, Rev3, Rev4, Rev5, Rev6]
