// Generated by gencpp from file ros_control_boilerplate/driverRequest.msg
// DO NOT EDIT!


#ifndef ROS_CONTROL_BOILERPLATE_MESSAGE_DRIVERREQUEST_H
#define ROS_CONTROL_BOILERPLATE_MESSAGE_DRIVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_control_boilerplate
{
template <class ContainerAllocator>
struct driverRequest_
{
  typedef driverRequest_<ContainerAllocator> Type;

  driverRequest_()
    : axis(0)
    , value(0)  {
    }
  driverRequest_(const ContainerAllocator& _alloc)
    : axis(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int16_t _axis_type;
  _axis_type axis;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct driverRequest_

typedef ::ros_control_boilerplate::driverRequest_<std::allocator<void> > driverRequest;

typedef boost::shared_ptr< ::ros_control_boilerplate::driverRequest > driverRequestPtr;
typedef boost::shared_ptr< ::ros_control_boilerplate::driverRequest const> driverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_control_boilerplate::driverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_control_boilerplate::driverRequest_<ContainerAllocator1> & lhs, const ::ros_control_boilerplate::driverRequest_<ContainerAllocator2> & rhs)
{
  return lhs.axis == rhs.axis &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_control_boilerplate::driverRequest_<ContainerAllocator1> & lhs, const ::ros_control_boilerplate::driverRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_control_boilerplate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "678e13c1fe4ebe3f4b3a3a1a5aee7968";
  }

  static const char* value(const ::ros_control_boilerplate::driverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x678e13c1fe4ebe3fULL;
  static const uint64_t static_value2 = 0x4b3a3a1a5aee7968ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_control_boilerplate/driverRequest";
  }

  static const char* value(const ::ros_control_boilerplate::driverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int16 axis\n"
"int32 value\n"
;
  }

  static const char* value(const ::ros_control_boilerplate::driverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct driverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_control_boilerplate::driverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_control_boilerplate::driverRequest_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.axis);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_CONTROL_BOILERPLATE_MESSAGE_DRIVERREQUEST_H
