// Generated by gencpp from file ros_control_boilerplate/requested_state.msg
// DO NOT EDIT!


#ifndef ROS_CONTROL_BOILERPLATE_MESSAGE_REQUESTED_STATE_H
#define ROS_CONTROL_BOILERPLATE_MESSAGE_REQUESTED_STATE_H

#include <ros/service_traits.h>


#include <ros_control_boilerplate/requested_stateRequest.h>
#include <ros_control_boilerplate/requested_stateResponse.h>


namespace ros_control_boilerplate
{

struct requested_state
{

typedef requested_stateRequest Request;
typedef requested_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct requested_state
} // namespace ros_control_boilerplate


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_control_boilerplate::requested_state > {
  static const char* value()
  {
    return "b06410045851cc21cdfe462a30e6cdb3";
  }

  static const char* value(const ::ros_control_boilerplate::requested_state&) { return value(); }
};

template<>
struct DataType< ::ros_control_boilerplate::requested_state > {
  static const char* value()
  {
    return "ros_control_boilerplate/requested_state";
  }

  static const char* value(const ::ros_control_boilerplate::requested_state&) { return value(); }
};


// service_traits::MD5Sum< ::ros_control_boilerplate::requested_stateRequest> should match
// service_traits::MD5Sum< ::ros_control_boilerplate::requested_state >
template<>
struct MD5Sum< ::ros_control_boilerplate::requested_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_control_boilerplate::requested_state >::value();
  }
  static const char* value(const ::ros_control_boilerplate::requested_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_control_boilerplate::requested_stateRequest> should match
// service_traits::DataType< ::ros_control_boilerplate::requested_state >
template<>
struct DataType< ::ros_control_boilerplate::requested_stateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_control_boilerplate::requested_state >::value();
  }
  static const char* value(const ::ros_control_boilerplate::requested_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_control_boilerplate::requested_stateResponse> should match
// service_traits::MD5Sum< ::ros_control_boilerplate::requested_state >
template<>
struct MD5Sum< ::ros_control_boilerplate::requested_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_control_boilerplate::requested_state >::value();
  }
  static const char* value(const ::ros_control_boilerplate::requested_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_control_boilerplate::requested_stateResponse> should match
// service_traits::DataType< ::ros_control_boilerplate::requested_state >
template<>
struct DataType< ::ros_control_boilerplate::requested_stateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_control_boilerplate::requested_state >::value();
  }
  static const char* value(const ::ros_control_boilerplate::requested_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_CONTROL_BOILERPLATE_MESSAGE_REQUESTED_STATE_H
