// Generated by gencpp from file RA_hardware_interface/feedbackResponse.msg
// DO NOT EDIT!


#ifndef RA_HARDWARE_INTERFACE_MESSAGE_FEEDBACKRESPONSE_H
#define RA_HARDWARE_INTERFACE_MESSAGE_FEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RA_hardware_interface
{
template <class ContainerAllocator>
struct feedbackResponse_
{
  typedef feedbackResponse_<ContainerAllocator> Type;

  feedbackResponse_()
    : position(0)  {
    }
  feedbackResponse_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct feedbackResponse_

typedef ::RA_hardware_interface::feedbackResponse_<std::allocator<void> > feedbackResponse;

typedef boost::shared_ptr< ::RA_hardware_interface::feedbackResponse > feedbackResponsePtr;
typedef boost::shared_ptr< ::RA_hardware_interface::feedbackResponse const> feedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator1> & lhs, const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator1> & lhs, const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RA_hardware_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ada70156e12e6e31948c64c60d8bb212";
  }

  static const char* value(const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xada70156e12e6e31ULL;
  static const uint64_t static_value2 = 0x948c64c60d8bb212ULL;
};

template<class ContainerAllocator>
struct DataType< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RA_hardware_interface/feedbackResponse";
  }

  static const char* value(const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 position\n"
"\n"
;
  }

  static const char* value(const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RA_hardware_interface::feedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RA_hardware_interface::feedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RA_HARDWARE_INTERFACE_MESSAGE_FEEDBACKRESPONSE_H
