// Generated by gencpp from file RA_hardware_interface/velocityResponse.msg
// DO NOT EDIT!


#ifndef RA_HARDWARE_INTERFACE_MESSAGE_VELOCITYRESPONSE_H
#define RA_HARDWARE_INTERFACE_MESSAGE_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RA_hardware_interface
{
template <class ContainerAllocator>
struct velocityResponse_
{
  typedef velocityResponse_<ContainerAllocator> Type;

  velocityResponse_()
    : result(false)  {
    }
  velocityResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct velocityResponse_

typedef ::RA_hardware_interface::velocityResponse_<std::allocator<void> > velocityResponse;

typedef boost::shared_ptr< ::RA_hardware_interface::velocityResponse > velocityResponsePtr;
typedef boost::shared_ptr< ::RA_hardware_interface::velocityResponse const> velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RA_hardware_interface::velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RA_hardware_interface::velocityResponse_<ContainerAllocator1> & lhs, const ::RA_hardware_interface::velocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RA_hardware_interface::velocityResponse_<ContainerAllocator1> & lhs, const ::RA_hardware_interface::velocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RA_hardware_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::RA_hardware_interface::velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RA_hardware_interface/velocityResponse";
  }

  static const char* value(const ::RA_hardware_interface::velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::RA_hardware_interface::velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RA_hardware_interface::velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RA_hardware_interface::velocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RA_HARDWARE_INTERFACE_MESSAGE_VELOCITYRESPONSE_H
