#!/usr/bin/env python

from __future__ import print_function

import rospy
from std_msgs.msg import String
import time
import math
from ODrive_Interface_test.srv import *

positions = [0, 0, 0, 0, 0, 0]

def drive_axis(req):
    print("Driving Axis " + str(req.axis) + ": " + str(req.value))
    positions[req.axis - 1] = req.value
    return driverResponse(True)

def axis_position(req):
    print("Axis Postition " + str(req.axis) + ": " + str(positions[req.axis - 1]))
    return feedbackResponse(positions[req.axis - 1])


rospy.init_node('driver')

driver = rospy.Service('drive_axis', driver, drive_axis)
feedback = rospy.Service('axis_position', feedback, axis_position)

rospy.spin()
