# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ deploy ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    
    runs-on: self-hosted

    steps:
      
      - name: mkdir
        run: |
          
    
      - name: Copy Files
        run: |
          scp -r ~/actions-runner/_work/NS-RobotArm/NS-RobotArm/NS-RobotArm/robot_ws noa-jetson@192.168.1.192:~/NS-RobotArm/
          scp -r ~/actions-runner/_work/NS-RobotArm/NS-RobotArm/NS-RobotArm/setup.sh noa-jetson@192.168.1.192:~/NS-RobotArm/
        
      - name: Setup
        run: |
          ssh noa-jetson@192.168.1.192 cd NS-RobotArm && sudo ./setup.sh

#ssh noa-jetson@192.168.1.192 
