# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ deploy ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    
    runs-on: self-hosted

    steps:
    
    - name: ssh
      run: |
        ssh noa-jetson@192.168.1.192 ./setup.sh

#ssh noa-jetson@192.168.1.192 
